coverage:
  status:
    project:
      default:
        target: 80%    # Minimum coverage required
        threshold: 1%  # Allow coverage to drop by 1%
    patch:
      default:
        target: 80%    # Minimum coverage for changed lines
        threshold: 1%

  ignore:
    - "tests/"        # Ignore test files from coverage
    - "docs/"         # Ignore documentation
    - "*.md"          # Ignore markdown files
    - ".github/"      # Ignore GitHub configuration

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

github_checks:
  annotations: true

test_analytics:
  # Enable test analytics features
  enabled: true
  
  # Alert on test failures
  alert:
    enabled: true
    stale: 7  # Mark tests as stale after 7 days without runs
  
  # Performance monitoring
  performance:
    enabled: true
    max_duration: 300  # Alert if tests take longer than 5 minutes