coverage:
  status:
    project:
      default:
        target: 80%    # Minimum coverage required
        threshold: 1%  # Allow coverage to drop by 1%
    patch:
      default:
        target: 80%    # Minimum coverage for changed lines
        threshold: 1%

  ignore:
    - "tests/"        # Ignore test files from coverage
    - "docs/"         # Ignore documentation
    - "*.md"          # Ignore markdown files
    - ".github/"      # Ignore GitHub configuration

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

github_checks:
  annotations: true